---
title: "Pratical Machine Learning Project"
author: "Kyle Maurice"
date: "December 23, 2015"
output: html_document
---

Setup the libraries that will be used

```{r}
library(caret)
library(dplyr)
set.seed(6540)
```

Load training and testing data sets

```{r}
training <- read.csv("pml-training.csv", stringsAsFactors=FALSE, na.strings = c("NA", "#DIV/0!", ""))
testing_final <- read.csv("pml-testing.csv", stringsAsFactors=FALSE, na.strings = c("NA", "#DIV/0!", ""))
```

Need to clean up column. There are a number of columns that have sparse data. 

```{r}
count.na <- function(x) {sum(is.na(x))}
temp <- training %>% summarize_each(funs(count.na))
temp <- temp[,temp[1,]<=1000]
colkeep<-names(temp)
training <- training %>% select(one_of(colkeep))
testing_final <- testing_final %>% select(one_of(colkeep))
testing_final <- testing_final %>% select(-one_of(c("X", "user_name", "raw_timestamp_part_1", "raw_timestamp_part_2", "cvtd_timestamp", "new_window")))
training <- training %>% select(-one_of(c("X", "user_name", "raw_timestamp_part_1", "raw_timestamp_part_2", "cvtd_timestamp", "new_window")))
training$classe <- factor(training$classe)
```


```{r}
inTrain <- createDataPartition(training, p=0.75, list=FALSE)
train <- training[inTrain]
test <- training[-inTrain]

```

```{r}

proj_model <- train(classe~., data=training, method="rf", tuneGrid=data.frame(mtry=3))
```
